			<div>
  {{$venue['id']}}<br>
  {{$venue['name']}}<br>
  {{$venue['slug']}}<br>
  {{$venue['category']}}<br>
  {{$venue['street_address']}}<br>
  {{$venue['city']}}<br>
  {{$venue['state']}}<br>
  {{$venue['zipcode']}}<br>
  {{$venue['lat']}}<br>
  {{$venue['lng']}}<br>
  {{$venue['phone']}}<br>
  {{$venue['email']}}<br>
  {{$venue['location']}}<br>
			</div>