			<div>
  {{$profile['id']}}<br>
  {{$profile['name']}}<br>
  {{$profile['slug']}}<br>
  {{$profile['category']}}<br>
  {{$profile['street_address']}}<br>
  {{$profile['city']}}<br>
  {{$profile['state']}}<br>
  {{$profile['zipcode']}}<br>
  {{$profile['lat']}}<br>
  {{$profile['lng']}}<br>
  {{$profile['phone']}}<br>
  {{$profile['email']}}<br>
  {{$profile['participant']}}<br>
  {{$profile['production']}}<br>
  {{$profile['canhavemembers']}}<br>
  {{$profile['canbeamember']}}<br>
  {{$profile['public']}}<br>
  {{$profile['confirmed']}}<br>
  {{$profile['created_at']}}<br>
  {{$profile['updated_at']}}<br>
  {{$profile['created_by']}}<br>
  {{$profile['updated_by']}}<br>
  {{$profile['location']}}<br>
			</div>